//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsManagerModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lunch
    {
        public int Id { get; set; }
        public int Week { get; set; }
        public string Day { get; set; }
        public string Deal { get; set; }
        public string SideLine { get; set; }
        public string Misc { get; set; }
        public string Sweet { get; set; }
    }
}
