//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventsManagerModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public int EmployeeID { get; set; }
        public int CommitteeID { get; set; }
    
        public virtual Committee Committee { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
