SET IDENTITY_INSERT [dbo].[Lunches] ON
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (4, 1, N'Monday', N'BBQ/Stream (Piece)', N'Chikar Channy', N'Roti+Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (5, 1, N'Tuesday', N'Chappal Kabaab', N'Daal Channa', N'Roti+Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (6, 1, N'Wednesday', N'Vegetable Pulao', N'Chicken Shami', N'Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (7, 1, N'Thursday', N'Haleem', NULL, N'Roti+Salad', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (8, 1, N'Friday', N'Chicken Pulao', N'Vegetable Kabaab', N'Salad+Raita', N'Kheer')
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (9, 2, N'Monday', N'Chicken Achari', N'Seasonal Vegetable', N'Roti+Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (10, 2, N'Tuesday', N'Beef Qorma/Nargisi Qufta', N'Daal Mash', N'Roti+Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (11, 2, N'Wednesday', N'Zeera Rice', N'Black Masar/Mong', N'Shaami+Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (12, 2, N'Thursday', N'Chicken Veg.', N'Red Beans', N'Roti+Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (13, 2, N'Friday', N'Fried Rice', N'Chicken Manchuria', NULL, N'Halwa')
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (14, 3, N'Monday', N'Chicken Karahi', N'Aloo Anndy', N'Roti+Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (15, 3, N'Tuesday', N'Aloo Chicken Naan', N'', N'Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (16, 3, N'Wednesday', N'Masala Rice', N'Chicken Chilli', NULL, NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (17, 3, N'Thursday', N'Alu Palak', N'White Beans/Channa', N'Roti+Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (18, 3, N'Friday', N'Chicken Biryani', NULL, N'Salad+Raita', N'Zarda')
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (19, 4, N'Monday', N'Chicken Qourma', N'Kalongi Aloo', N'Roti+Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (20, 4, N'Tuesday', N'Fried Seekh Kabab/Qeema Shimla', N'Daal Channa', N'Roti+Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (21, 4, N'Wednesday', N'Rice', N'Daal Mong/Aloo Kabab', N'Salad+Raita', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (22, 4, N'Thursday', N'Chowmian', N'Honey Wings', N'Channa Salad', NULL)
INSERT INTO [dbo].[Lunches] ([Id], [Week], [Day], [Deal], [SideLine], [Misc], [Sweet]) VALUES (23, 4, N'Friday', N'MFC Pulao', N'Chicken Piece', N'Salad+Raita', N'Sawiyan')
SET IDENTITY_INSERT [dbo].[Lunches] OFF
